#!/usr/bin/env bash

step=5

for arg in "$@"
do
	case $arg in
		--increment | -i)
			amixer -q sset Master $step%+
			;;
		--decrement | -d)
			amixer -q sset Master $step%-
			;;
		--toggle | -t)
			amixer -q sset Master toggle
	esac
	shift
done
